name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Render PCB PDF
      run: docker run -v `pwd`/hardware:/root/project -v `pwd`/output:/root/output alexluberg/kicad:nightly python3 pcbnew_automation/plot.py --file_format pdf /root/project/led-ring-mic.kicad_pcb /root/output/pcb_pdf/    
    - name: Build Gerbers zip archive
      run: docker run -v `pwd`/hardware:/root/project -v `pwd`/output:/root/output alexluberg/kicad:nightly pcbnew_automation/plot.py --file_format zip_gerbers /root/project/led-ring-mic.kicad_pcb /root/output/gerbers/
    - name: Render Schematic PDF
      run: docker run -v `pwd`/hardware:/root/project -v `pwd`/output:/root/output alexluberg/kicad:nightly python -m eeschema.schematic export -a --file_format pdf /root/project/led-ring-mic.sch /root/output/schematic_pdf

    - uses: actions/upload-artifact@v1
      with:
        name: Gerbers ZIP
        path: ./output/gerbers/led-ring-mic_gerbers.zip
    - uses: actions/upload-artifact@v1
      with:
        name: Schematic PDF
        path: ./output/schematic_pdf/led-ring-mic.pdf
    - uses: actions/upload-artifact@v1
      with:
        name: PDF PCB
        path: ./output/pcb_pdf/led-ring-mic.pdf
