name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Gerbers
      run: |
        docker run -v ./hardware:/root/project -v ./output:/root/output -it alexluberg/kicad:nightly python3 pcbnew_automation/plot.py --file_format pdf /root/project/led-ring-mic.kicad_pcb /root/output/pcb_pdf/    
    - uses: actions/upload-artifact@v1
      with:
          name: PDF PCB
          path: ./output/pcb_pdf/led-ring-mic.pdf
